
package jeffbernsen.universityparkingsystem;

import java.util.ArrayList;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class AddressTest {
    
    public AddressTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

   /** 
    * Custom built test for the Address class
    */
    
  public static void main( String[] args ) {
    var addressOne = new Address( "1600 Penn Ave", "", "Washington", "D.C.", "20500", "WhiteHouse" );
    var addressToPrint = addressOne.getAddress();
    System.out.println( addressToPrint );
  }
      
    /**
     * Test of getAddress method, of class Address.
     * * Autogenerated by NetBeans JUnit plugin.
     */
    /** 
    @Test
    public void testGetAddress() {
        System.out.println("getAddress");
        Address instance = null;
        ArrayList<String> expResult = null;
        ArrayList<String> result = instance.getAddress();
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    */
    /**
     * Test of setAddress method, of class Address.
     * Autogenerated by NetBeans JUnit plugin.
     */
    /* @Test
    public void testSetAddress() {
        System.out.println("setAddress");
        ArrayList<String> address = null;
        Address instance = null;
        instance.setAddress(address);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    */
}
