package jeffbernsen.universityparkingsystem;

import java.util.ArrayList;
import java.util.Arrays;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class CustomerTest {
    
    public CustomerTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }
    
    /**
     * Custom built test to build Customer object and test getCustomer() and setCustomer() methods
    */
    @Test
    public static void main( String[] args ) {
      var customerOne = new Customer( "1", "Mr", "Somebody", "555-555-1212", "Somewhere" );
      var customerToPrint = customerOne.getCustomer();    
      System.out.println( customerToPrint );
      ArrayList< String > customerOneUpdate = new ArrayList<String>(Arrays.asList(
              "2", "Mr", "Nobody", "800-456-7890", "Nowhere"));
      customerOne.setCustomer( customerOneUpdate );
      customerToPrint = customerOne.getCustomer();
      System.out.println( customerToPrint );
    }
    
    /**
     * Test of getCustomerInfo method, of class Customer.
     * Autogenerated by NetBeans JUnit plugin.
    @Test
    public void testGetCustomerInfo() {
        System.out.println("getCustomerInfo");
        Customer instance = null;
        ArrayList<String> expResult = null;
        ArrayList<String> result = instance.getCustomerInfo();
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
     */


    /**
     * Test of setCustomerInfo method, of class Customer.
     * Autogenerated by NetBeans JUnit plugin.
    @Test
    public void testSetCustomerInfo() {
        System.out.println("setCustomerInfo");
        ArrayList<String> customer = null;
        Customer instance = null;
        instance.setCustomerInfo(customer);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
     */

    
}
