package jeffbernsen.universityparkingsystem;

import java.util.Date;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class DateUtilityTest {
    
    public DateUtilityTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    /**
     * Test of parseDate method, of class DateUtility.
     * Autogenerated by NetBeans JUnit plugin.
     */
    @Test
    public void testParseDate() {
        System.out.println("parseDate");
        String date = "2020-04-20";
        Date expResult = new Date("2020-04-20");
        Date result = DateUtility.parseDate(date);
        assertEquals(expResult, result);
    }
    
}
