package jeffbernsen.universityparkingsystem;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class ParkingLotTest {
    
    public ParkingLotTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    /**
     * This is a custom built test. 
     * This main method tests the ParkingLot object instantiation and creation of parkingLotList
     * and the following methods on those objects:
     *     buildParkingLotListInputs()
     *     setParkingLotRate()
     *     parkingLotList.add()
     *     setParkingLotAddress()
     */
    @Test
    public static void main( String[] args ) {
      // Construct a couple parkingLots and add them to the array list of parking lots
      // parkingLot #1
      ArrayList< Object > parkingLotList = new ArrayList<>();
      var parkingLotOne = new ParkingLot( "General Lot 119", 1 );
      parkingLotOne.setParkingLotRate(4.50);
      ArrayList< Object > inputOne = new ArrayList<>();
      inputOne = parkingLotOne.buildParkingLotListInputs( parkingLotOne );
      
      // parkingLot #2
      var parkingLotTwo = new ParkingLot( "General Lot 87", 2 );
      parkingLotOne.setParkingLotRate(6.00);
      ArrayList< Object > inputTwo = new ArrayList<>();
      inputTwo = parkingLotTwo.buildParkingLotListInputs( parkingLotTwo );
    
      // add the parkingLots to the list of parkingLots
      parkingLotList.add( inputOne );
      parkingLotList.add( inputTwo );
    
      // check setParkingLotAddress()
      // create two address objects
      Address parkingLotOneAddress = new Address( "2100 East Wesley Avenue", "", "Denver", "CO", "", 
            "General Lot 119" );
      Address parkingLotTwoAddress = new Address( "1470 North 19th Street", "", "Denver", "CO", "", 
            "General Lot 87" );
      // call setParkingLotAddress() on the two parkingLot objects
      parkingLotOne.setParkingLotAddress( parkingLotOneAddress );
      parkingLotTwo.setParkingLotAddress( parkingLotTwoAddress );
    
      // assign the Addresses to a variable
      Address address1 = parkingLotOne.getParkingLotAddress();
      Address address2 = parkingLotTwo.getParkingLotAddress();
      // print out the Addresses
      System.out.println( "ParkingLot variable parkingLotOne Address, " + 
              Arrays.asList( parkingLotOneAddress.address ) + " should equal " + 
              Arrays.asList( address1.address ) +
              " with the seParkingLotAddress() and getParkingLotAddress() methods called " +
              "on parkingLotOne.");
      System.out.println( "ParkingLot variable parkingLotTwo Address, " + 
              Arrays.asList( parkingLotTwoAddress.address ) + " should equal " + 
              Arrays.asList( address2.address ) +
              " with the seParkingLotAddress() and getParkingLotAddress() methods called " +
              "on parkingLotTwo.");
    
      // or add the address to the inputOne arrayList
      inputOne.add(2, parkingLotOneAddress );
      inputTwo.add(2, parkingLotTwoAddress );
    
      System.out.println( Arrays.asList( parkingLotOneAddress.address ) );
    
  }
  
    /**
     * Test of getDailyRate method, of class ParkingLots.
     * Autogenerated by NetBeans JUnit plugin.
     * 
    @Test
    public void testGetDailyRate() {
        System.out.println("getDailyRate");
        String CarType = "";
        ParkingLots instance = null;
        double expResult = 0.0;
        double result = instance.getDailyRate(CarType);
        assertEquals(expResult, result, 0.0);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
      */
}
