package jeffbernsen.universityparkingsystem;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class ParkingTransactionTest {
    
    public ParkingTransactionTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }
    
    @Test
    /**
     * Custom built test to test the ParkingTransaction class.    
    */
    public static void main( String[] args ) {
      // create Customer object for the Car object
      Customer cust5 = new Customer ( "", "Slim", "", "", "" );
      // create Car object for the Permit object
      Car car1 = new Car( cust5, "123ABC", "COMPACT" ); 
      // create Permit object to complete transaction
      ParkingPermit permit1 = new ParkingPermit( "P0001", car1 ); 
      // create new ParkingLot object to set and use dailyRate
      ParkingLot lot1 = new ParkingLot( "Red Lot", 1 );
      // set the ParkingLotRate
      lot1.setParkingLotRate( 3.25 ); 
      var event = new ParkingTransaction();
      System.out.println( permit1.getIdPermit() + " is charged " + 
            String.valueOf( event.getChargedAmount( lot1, permit1 ) ) + " for parking in " + 
              lot1.getParkingLotName() + " on " + event.getTransactionDate() );
    }
    
    /**
     * Test of getParkingLotDailyRate method, of class ParkingTransaction.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetParkingLotDailyRate() {
//        System.out.println("getParkingLotDailyRate");
//        ParkingLot parkingLot = null;
//        ParkingTransaction instance = new ParkingTransaction();
//        double expResult = 0.0;
//        double result = instance.getParkingLotDailyRate(parkingLot);
//        assertEquals(expResult, result, 0.0);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of getIdPermit method, of class ParkingTransaction.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetIdPermit() {
//        System.out.println("getIdPermit");
//        ParkingPermit permit = null;
//        ParkingTransaction instance = new ParkingTransaction();
//        String expResult = "";
//        String result = instance.getIdPermit(permit);
//        assertEquals(expResult, result);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of getChargedAmount method, of class ParkingTransaction.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetChargedAmount() {
//        System.out.println("getChargedAmount");
//        ParkingLot parkingLot = null;
//        ParkingPermit permit = null;
//        ParkingTransaction instance = new ParkingTransaction();
//        Money expResult = null;
//        Money result = instance.getChargedAmount(parkingLot, permit);
//        assertEquals(expResult, result);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

}
