package jeffbernsen.universityparkingsystem;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class ParkingPermitTest {
    
    public ParkingPermitTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }
    
    @Test
//    Custom built test  to check if the methods in Car class are working
    public static void main( String[] args ) {
      // build a Customer object for the Car object
      Customer cust3 = new Customer ( "", "Tim", "", "", "" );
      // build a Car object for the Car ParkingPermit object
      Car kar = new Car( cust3, "123DEF", "SUV" );
      ParkingPermit p = new ParkingPermit( "S1001", kar );
      p.setExpiration( "2021-06-01" );
      System.out.println( p.getCarOwner() );
      System.out.println( p.getCarType() );
      System.out.println( p.getExpiration() );
      System.out.println( p.getIdPermit() );
      p.setExpiration( "2021-08-01" );
      p.setIdPermit( "S2001" );
      System.out.println( p.getExpiration() );
      System.out.println( p.getIdPermit() );
  }


    /**
     * Test of setIdPermit method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testSetIdPermit() {
//        System.out.println("setIdPermit");
//        String idPermit = "";
//        ParkingPermit instance = null;
//        instance.setIdPermit(idPermit);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of getIdPermit method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetIdPermit() {
//        System.out.println("getIdPermit");
//        ParkingPermit instance = null;
//        String expResult = "";
//        String result = instance.getIdPermit();
//        assertEquals(expResult, result);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of getCarType method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetCarType() {
//        System.out.println("getCarType");
//        ParkingPermit instance = null;
//        String expResult = "";
//        String result = instance.getCarType();
//        assertEquals(expResult, result);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of setExpiration method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testSetExpiration() {
//        System.out.println("setExpiration");
//        String expiration = "";
//        ParkingPermit instance = null;
//        instance.setExpiration(expiration);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of getExpiration method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testGetExpiration() {
//        System.out.println("getExpiration");
//        ParkingPermit instance = null;
//        String expResult = "";
//        String result = instance.getExpiration();
//        assertEquals(expResult, result);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }

    /**
     * Test of main method, of class ParkingPermit.
     * Autogenerated by NetBeans JUnit plugin.
     */
//    @Test
//    public void testMain() {
//        System.out.println("main");
//        String[] args = null;
//        ParkingPermit.main(args);
//        // TODO review the generated test code and remove the default call to fail.
//        fail("The test case is a prototype.");
//    }
    
}
