package jeffbernsen.universityparkingsystem;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Collections;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author jeffb
 */
public class ParkingOfficeTest {
    
    public ParkingOfficeTest() {
    }
    
    @BeforeClass
    public static void setUpClass() {
    }
    
    @AfterClass
    public static void tearDownClass() {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    /**
     * Test of getParkingOfficeName method, of class ParkingOffice.
     * Autogenerated by NetBeans JUnit plugin.
     */
    /*
    @Test
    public void testGetParkingOfficeName() {
        System.out.println("getParkingOfficeName");
        ParkingOffice instance = null;
        String expResult = "";
        String result = instance.getParkingOfficeName();
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    */
    
    @Test
    public static void main ( String[] args) {
      // Address object to instantiate ParkingOffice object
      Address mainOfficeAddress = new Address( "1", "", "Denver", "CO", "67001", "A001" );
      ParkingOffice mainOffice = new ParkingOffice( mainOfficeAddress );
      List< Customer > listOfCustomers = new ArrayList< >();
      ArrayList< Object > listOfCars = new ArrayList< Object >();
      
      System.out.println( "registerCustomer" );
      // customer #1 to add to list of customers
      Customer cust1 = new Customer( "C001", "Jim", "", "", "" );
      // customer #2 to add to list of customers
      Customer cust2 = new Customer( "C002", "Slim", "", "", "" );
      
      mainOffice.registerCustomer( cust1 );
      mainOffice.registerCustomer( cust2 );
      
            System.out.println( " registerCar " );
      // Set the value for the idPermit
      String idPermitOne = "P001";
      // Customer object for the Car object
      Customer custThree = new Customer( "C003", "Kim", "", "", "" );
      // Car object to register
      Car carOne = new Car( custThree, "123ABC", "COMPACT" );
      mainOffice.registerCar( idPermitOne, carOne );

      System.out.println( "parkEvent" );
      ParkingLot parkingLotOne = new ParkingLot( "Parking Lot 1", 1 );
      ParkingPermit permitOne = new ParkingPermit( idPermitOne, carOne );
      mainOffice.park(parkingLotOne, permitOne);
      
      System.out.println( "chargesByPermit" );
      mainOffice.chargesByPermit( permitOne );
      
      System.out.println( "chargesByCustomer" );
      mainOffice.chargesByCustomer( custThree );
    }
}
